name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Prepare Node.js
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Perform linting
        run: npm run lint
